#db_path = "~/.local/share/atuin/history.db"
#key_path = "~/.local/share/atuin/key"
# The path to the Atuin server session file. This is essentially just an API token
#session_path = "~/.local/share/atuin/session"
dialect = "us"
auto_sync = true
update_check = true
sync_address = "https://mw.je/atuin"
sync_frequency = "1h"
keymap_mode = "vim-insert"
prefers_reduced_motion = true
show_preview = true
# pressing <Enter> leaves the search view and runs the command
enter_accept = true
exit_mode = "return-query"
store_failed = true
scroll_exits = false

search_mode = 'fuzzy'
# can press ctrl-r again when in the search view to cycle through filter modes
filter_mode = 'host'
search_mode_shell_up_key_binding = 'fuzzy'
filter_mode_shell_up_key_binding = 'directory'

# ignore anything that ends with `# atuin:ignore`
history_filter = [
    '# atuin:ignore$',
]

[sync]
records = true

[dotfiles]
enabled = false
